In [1]:
import numpy as np

In [10]:
a1 = np.array([1,2,3])

In [12]:
a2 = np.array ([[1,2,3],[4,5,6]])

In [13]:
a3 = np.array ([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [18]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [19]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 3), 2, dtype('int32'), 9, numpy.ndarray)

In [20]:
import pandas as pd
df = pd.DataFrame(a2)

In [21]:
df

0  1  2
0  1  2  3
1  4  5  6

In [23]:
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
range_array = np.arange (0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
random_array = np.random.randint(10, size = (7,2))
random_array

array([[5, 5],
       [6, 6],
       [8, 0],
       [0, 5],
       [3, 1],
       [0, 4],
       [1, 3]])

In [31]:
np.random.random((3,5))

array([[0.76400937, 0.54448654, 0.18083392, 0.97180516, 0.52709332],
       [0.67760336, 0.64356647, 0.52936941, 0.4457148 , 0.16846554],
       [0.51378014, 0.01197367, 0.96338   , 0.42946211, 0.7042653 ]])

In [33]:
np.random.seed(42)

In [36]:
np.random.randint(10,size=(4,6))

array([[6, 7, 2, 0, 3, 1],
       [7, 3, 1, 5, 5, 9],
       [3, 5, 1, 9, 1, 9],
       [3, 7, 6, 8, 7, 4]])

In [37]:
array = np.random.randint(1,10, size = (3,7))

In [38]:
np.unique(array)

array([1, 2, 3, 5, 7, 8, 9])